M48
; DRILL file {KiCad (6.0.1)} date Fri 11 Feb 2022 20:30:24 GMT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-11T20:30:24+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X120.396Y-84.78
T2
X81.28Y-47.615
X81.28Y-84.445
T0
M30
